### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by TheJun1999** [geekjuruo/LEAD#4]
运行时出现这样的错误，请问我该怎么处理它呢？
100%|██████████| 284201/284201 [00:01<00:00, 192911.68it/s]
Train Size: 284201, Valid Train Size: 0
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/remote-home/cs_tcci_renjun/RENJUN/LEAD-main/main.py", line 49, in <module>
    pipeline.initialize()
  File "/remote-home/cs_tcci_renjun/RENJUN/LEAD-main/pipeline/BasicPipeline.py", line 107, in initialize
    self.get_loader()
  File "/remote-home/cs_tcci_renjun/RENJUN/LEAD-main/pipeline/BasicPipeline.py", line 69, in get_loader
    self.data_loaders[key] = DataLoader(dataset=value, collate_fn=lambda data: self.processor.process(data, key), shuffle=shuffle, drop_last=False, batch_size=batch_size)
  File "/remote-home/cs_tcci_renjun/envs/rjlead/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 277, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/remote-home/cs_tcci_renjun/envs/rjlead/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 97, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by masr2000** [comment]
多次运行程序时会使用之前预处理过程的数据缓存，由于缓存过程中使用了python的hash函数作为key，因此多次运行程序时请固定PYTHONHASHSEED环境变量为固定值。

**Comment by TheJun1999** [comment]
感谢大佬指教
